version: '3'

services:

  dispatcher:
    image: multimoml/dispatcher:latest
    container_name: dispatcher
    restart: unless-stopped
    networks:
      - products-db
      - traefik-proxy
#    ports:
#      - "6001:6001"
    environment:

      # MongoDB
      M_USERNAME: ${M_USERNAME}
      M_PASSWORD: ${M_PASSWORD}
      DATABASE: ${DATABASE}

      # Dispatcher
      ENVIRONMENT: "prod"
      M_SERVER: products-db:27017
      RUN_INTERVAL: 14400 # 4h in seconds
      PORT: 6001
    labels:
      traefik.enable: true
      traefik.docker.network: traefik-proxy # needed if you have multiple networks and no default
      traefik.http.routers.extractor-timer.rule: Host(`dispatcher.${DOMAIN}`)
      traefik.http.routers.extractor-timer.entrypoints: https
      traefik.http.services.extractor-timer.loadbalancer.server.port: 6001

networks:
  products-db:
    external: true
  traefik-proxy:
    external: true
