version: '3'

services:

  dispatcher:
    build: .
    container_name: dispatcher
    restart: unless-stopped
    networks:
      - traefik-proxy
      - products-db
    ports:
      - "6001:6001"
    environment:
      ENVIRONMENT: prod
      DOMAIN: multimo.ml
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      DB_NAME: products
      CONFIG_SERVER: http://multimo.dedyn.io
      CONFIG_SERVER_PORT: 30001
      PORT: 6001
    labels:
      traefik.enable: true
      traefik.docker.network: traefik-proxy # needed if you have multiple networks and no default
      traefik.http.routers.qr-generator.rule: Host(`${DOMAIN}`) && PathPrefix(`/products/`)
      traefik.http.routers.qr-generator.entrypoints: https
      traefik.http.services.qr-generator.loadbalancer.server.port: 6001
    depends_on:
      - products-db
    volumes:
      - ./.env:/.env

networks:
  products-db:
    external: true
  traefik-proxy:
    external: true