apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
      - name: dispatcher
        image: ghcr.io/multimoml/dispatcher:latest
        env:
        - name: ACTIVE_ENV
          value: "prod"
        - name: DB_USERNAME
          value: "rso"
        - name: DB_HOST
          value: "private-prod-f6ec1227.mongo.ondigitalocean.com"
        - name: DB_NAME
          value: "products"
        - name: PORT
          value: "6001"
        - name: DB_PASSWORD
          value: "<DB_PASSWORD>"
        - name: CONFIG_SERVER
          value: "https://configs.multimo.ml"
        ports:
        - containerPort: 6001
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /products/live
            port: server
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /products/ready
            port: server
          initialDelaySeconds: 10
          periodSeconds: 3
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
      terminationGracePeriodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: dispatcher
spec:
  type: ClusterIP
  ports:
  - port: 6001
    targetPort: server
  selector:
    app: dispatcher
